In [14]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import neighbors
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("train.csv")
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
le = preprocessing.LabelEncoder()
le.fit(dataset["Sex"])
dataset["Sex"] = le.transform(dataset["Sex"])
le.fit(dataset["Embarked"])
dataset["Embarked"] = le.transform(dataset["Embarked"])
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [4]:
y  = dataset["Pclass"]
X = dataset.drop(["Pclass","PassengerId","Name","Ticket","Cabin"],axis=1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [13]:
def K_value(k):
    knn=neighbors.KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train).score(X_test,y_test)
    y_pred=knn.predict(X_test)
    print("\nConfusion matrix when k = ",k,":\n",confusion_matrix(y_test,y_pred))
    print("Accuracy is when k = ",k,":",accuracy_score(y_test,y_pred,normalize=True))
    
for i in range(1,268):
    K_value(i)


Confusion matrix when k =  1 :
 [[ 62   6   2]
 [  3  37   9]
 [  1   8 139]]
Accuracy is when k =  1 : 0.8913857677902621

Confusion matrix when k =  2 :
 [[ 67   2   1]
 [  8  37   4]
 [  4  17 127]]
Accuracy is when k =  2 : 0.8651685393258427

Confusion matrix when k =  3 :
 [[ 63   5   2]
 [  7  28  14]
 [  3   5 140]]
Accuracy is when k =  3 : 0.8651685393258427

Confusion matrix when k =  4 :
 [[ 61   7   2]
 [  8  30  11]
 [  4  15 129]]
Accuracy is when k =  4 : 0.8239700374531835

Confusion matrix when k =  5 :
 [[ 58  10   2]
 [  7  28  14]
 [  3   9 136]]
Accuracy is when k =  5 : 0.8314606741573034

Confusion matrix when k =  6 :
 [[ 64   5   1]
 [  7  32  10]
 [  3  15 130]]
Accuracy is when k =  6 : 0.846441947565543

Confusion matrix when k =  7 :
 [[ 59  10   1]
 [  7  28  14]
 [  3   7 138]]
Accuracy is when k =  7 : 0.8426966292134831

Confusion matrix when k =  8 :
 [[ 61   8   1]
 [  7  34   8]
 [  3  13 132]]
Accuracy is when k =  8 : 0.850187265917603

Confusion


Confusion matrix when k =  69 :
 [[ 56   7   7]
 [  5  11  33]
 [  5   6 137]]
Accuracy is when k =  69 : 0.7640449438202247

Confusion matrix when k =  70 :
 [[ 57   6   7]
 [  5  11  33]
 [  5   7 136]]
Accuracy is when k =  70 : 0.7640449438202247

Confusion matrix when k =  71 :
 [[ 57   6   7]
 [  5  11  33]
 [  5   7 136]]
Accuracy is when k =  71 : 0.7640449438202247

Confusion matrix when k =  72 :
 [[ 56   7   7]
 [  5  11  33]
 [  5   8 135]]
Accuracy is when k =  72 : 0.7565543071161048

Confusion matrix when k =  73 :
 [[ 56   7   7]
 [  5  11  33]
 [  5   6 137]]
Accuracy is when k =  73 : 0.7640449438202247

Confusion matrix when k =  74 :
 [[ 57   6   7]
 [  5  11  33]
 [  5   6 137]]
Accuracy is when k =  74 : 0.7677902621722846

Confusion matrix when k =  75 :
 [[ 56   7   7]
 [  5  11  33]
 [  5   6 137]]
Accuracy is when k =  75 : 0.7640449438202247

Confusion matrix when k =  76 :
 [[ 56   7   7]
 [  5  11  33]
 [  5   5 138]]
Accuracy is when k =  76 : 0.767790262


Confusion matrix when k =  136 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
Accuracy is when k =  136 : 0.7602996254681648

Confusion matrix when k =  137 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
Accuracy is when k =  137 : 0.7602996254681648

Confusion matrix when k =  138 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
Accuracy is when k =  138 : 0.7602996254681648

Confusion matrix when k =  139 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
Accuracy is when k =  139 : 0.7602996254681648

Confusion matrix when k =  140 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
Accuracy is when k =  140 : 0.7602996254681648

Confusion matrix when k =  141 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
Accuracy is when k =  141 : 0.7602996254681648

Confusion matrix when k =  142 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   4 139]]
Accuracy is when k =  142 : 0.7565543071161048

Confusion matrix when k =  143 :
 [[ 52  13   5]
 [  5  11  33]
 [  5   4 139]]
Accuracy is when k =  1

Accuracy is when k =  202 : 0.7228464419475655

Confusion matrix when k =  203 :
 [[ 48   6  16]
 [  4   2  43]
 [  5   0 143]]
Accuracy is when k =  203 : 0.7228464419475655

Confusion matrix when k =  204 :
 [[ 48   6  16]
 [  4   2  43]
 [  5   0 143]]
Accuracy is when k =  204 : 0.7228464419475655

Confusion matrix when k =  205 :
 [[ 48   6  16]
 [  4   2  43]
 [  5   0 143]]
Accuracy is when k =  205 : 0.7228464419475655

Confusion matrix when k =  206 :
 [[ 48   6  16]
 [  4   2  43]
 [  5   0 143]]
Accuracy is when k =  206 : 0.7228464419475655

Confusion matrix when k =  207 :
 [[ 48   6  16]
 [  4   2  43]
 [  5   0 143]]
Accuracy is when k =  207 : 0.7228464419475655

Confusion matrix when k =  208 :
 [[ 48   6  16]
 [  4   2  43]
 [  5   0 143]]
Accuracy is when k =  208 : 0.7228464419475655

Confusion matrix when k =  209 :
 [[ 48   6  16]
 [  4   2  43]
 [  5   0 143]]
Accuracy is when k =  209 : 0.7228464419475655

Confusion matrix when k =  210 :
 [[ 48   5  17]
 [  4  


Confusion matrix when k =  267 :
 [[ 47   1  22]
 [  4   1  44]
 [  5   0 143]]
Accuracy is when k =  267 : 0.7153558052434457


# From above Observation k = 1 gives more accuracy than other values.