# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [3]:
x = np.random.random((3,3,3))
print(x)

[[[0.15252796 0.87469529 0.05894754]
  [0.75651597 0.72321396 0.28471195]
  [0.03265713 0.27479286 0.63228301]]

 [[0.79324071 0.51942394 0.94612039]
  [0.12108624 0.28537851 0.08726282]
  [0.34991526 0.87348087 0.31069989]]

 [[0.60873601 0.13516512 0.53418039]
  [0.20261593 0.20813704 0.20179194]
  [0.99828648 0.62426699 0.22445848]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
s = np.zeros((8,8), dtype=int)
s[1::2, ::2]=1
s[::2, 1::2]=1
print(s)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [3]:
n= np.random.random((5,5))
print("Original Array:\n")
print(n)
nmax, nmin = n.max(), n.min()
n = (n - nmin)/(nmax - nmin)
print("\nAfter normalization:\n")
print(n)

Original Array:

[[0.30935413 0.55193685 0.4847795  0.26930181 0.78918187]
 [0.34546578 0.16061834 0.91349347 0.54949623 0.59673044]
 [0.45584695 0.98676168 0.5658416  0.72717638 0.24603578]
 [0.98512813 0.95040847 0.17241881 0.96843369 0.12986823]
 [0.69869409 0.55575134 0.7026603  0.50248088 0.54515515]]

After normalization:

[[0.20946117 0.49255671 0.41418366 0.16271986 0.76942313]
 [0.25160369 0.03588557 0.91449554 0.48970849 0.54483111]
 [0.38041919 1.         0.50878365 0.69706234 0.13556825]
 [0.99809363 0.95757558 0.04965679 0.97861111 0.        ]
 [0.66382333 0.49700824 0.66845192 0.43484129 0.48464243]]


# 5.  How to find common values between two arrays?

In [4]:
arr1 = np.array([70, 50, 200, 40, 60])
print("Arr1: ",arr1)
arr2 = [100, 50, 40, 90]
print("Arr2: ",arr2)
print("\nCommon values between two arrays:")
print(np.intersect1d(arr1, arr2))

Arr1:  [ 70  50 200  40  60]
Arr2:  [100, 50, 40, 90]

Common values between two arrays:
[40 50]


# 6.How to get the dates of yesterday, today and tomorrow?

In [15]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [3]:
x = np.random.randint(0,5,6)
print("First array:")
print(x)
y = np.random.randint(0,5,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[3 3 3 1 0 1]
Second array:
[0 3 3 4 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [5]:
n= np.random.random((10))
print("Original Arrays:\n ")
print(n)
n[n.argmax()] = 0
print("\nMaximum value replaced by 0:\n")
print(n)

Original Arrays:
 
[0.1118214  0.34359217 0.57992791 0.02344045 0.06671609 0.68353262
 0.86565286 0.39349336 0.81922531 0.80835922]

Maximum value replaced by 0:

[0.1118214  0.34359217 0.57992791 0.02344045 0.06671609 0.68353262
 0.         0.39349336 0.81922531 0.80835922]


# 9. How to print all the values of an array?

In [6]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.ones((8,8))
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


# 10.Subtract the mean of each row of a matrix

In [15]:
d = np.random.rand(4,5)
print("Original Matrix:\n ")
print(d)
print("\nAfter subtracting the mean of each row of a matrix:\n")
e = d-d.mean(axis=1, keepdims=True)
print(e)

Original Matrix:
 
[[0.01646787 0.27315546 0.47600627 0.75761898 0.42889726]
 [0.17481597 0.18153522 0.27669861 0.34278409 0.05370857]
 [0.94591536 0.74527612 0.76185747 0.5534309  0.93885451]
 [0.34735931 0.81492837 0.96395668 0.11631002 0.31989853]]

After subtracting the mean of each row of a matrix:

[[-0.3739613  -0.11727371  0.08557711  0.36718981  0.03846809]
 [-0.03109252 -0.02437327  0.07079012  0.1368756  -0.15219992]
 [ 0.15684849 -0.04379075 -0.0272094  -0.23563597  0.14978764]
 [-0.16513127  0.30243778  0.4514661  -0.39618057 -0.19259205]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [3]:
Z = np.ones(20)
I = np.random.randint(0,len(Z),30)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[6. 3. 2. 3. 3. 1. 3. 2. 1. 1. 1. 2. 1. 4. 3. 2. 3. 2. 2. 5.]


# 12.How to get the diagonal of a dot product?

In [3]:
A = np.random.randint(0,15,(4,4))
B= np.random.randint(0,15,(4,4))
np.diag(np.dot(A, B))

array([ 93, 318, 210, 247])

# 13.How to find the most frequent value in an array?

In [5]:
Z = np.random.randint(0,10,30)
print (Z)
print('Most Frequent Value:', np.bincount(Z).argmax())

[7 1 7 6 9 3 1 0 3 4 5 8 5 7 7 1 4 4 1 5 8 6 5 8 2 4 6 8 4 7]
Most Frequent Value: 4


# 14.How to get the n largest values of an array

In [11]:
Z = np.arange(1000)
np.random.shuffle(Z)
n = 6
print (Z[np.argsort(Z)[-n:]])

[994 995 996 997 998 999]


# 15.How to create a record array from a regular array?

In [15]:
Z = np.array([("Hello", 8.5, 7),
              ("World", 9.6, 4)])
R = np.core.records.fromarrays(Z.T,
                               names='num1, num2, num3',
                               formats = 'S8, f8, i8')
R

rec.array([(b'Hello', 8.5, 7), (b'World', 9.6, 4)],
          dtype=[('num1', 'S8'), ('num2', '<f8'), ('num3', '<i8')])